### ISSUE TITLE
Clarification about pretrained model naming

### ISSUE THREAD

**Issue by MahmoudAshraf97** [BUTSpeechFIT/DiaPer#7]
Hello and thanks for your work and sharing the pretrained models
1. I noticed that all the models shared have `2spk` in their names, does that mean that they only support two speakers?
2. If I want to use the best model for a variety of scenarios, Ideally I would've used the model finetuned on the largest amount of data, but what I understood is that each checkpoint is only finetuned on a single dataset, does averaging the weights of all of the finetuned checkpoints do the job? or at least will it be better than the non finetuned checkpoint across the datasets?

**Comment by fnlandini** [comment]
Hello @MahmoudAshraf97 thank you for the kind words.

1. I am sorry if the naming convention was not so clear. Taking these models as an example, the names mean the following:
[SC_LibriSpeech_2spk](https://github.com/BUTSpeechFIT/DiaPer/tree/main/models/10attractors/SC_LibriSpeech_2spk) was trained only with 2 speakers, so even though you can use the same model for recordings with more speakers, it will only find 2.
[SC_LibriSpeech_2spk_adapted1-10](https://github.com/BUTSpeechFIT/DiaPer/tree/main/models/10attractors/SC_LibriSpeech_2spk_adapted1-10) is the previous model but adapted with data having between 1 and 10 speakers. This one should be able to better handle recordings with up to 10 speakers.
[SC_LibriSpeech_2spk_adapted1-10_finetuneAISHELL4mix](https://github.com/BUTSpeechFIT/DiaPer/tree/main/models/10attractors/SC_LibriSpeech_2spk_adapted1-10_finetuneAISHELL4mix) is the previous model but fine-tuned with AISHELL4 data. It will probably be equally capable of dealing with up to 10 speakers but better suited for data like AISHELL4.

2. If you want to use one model for different scenarios, my suggestion is that you fine-tune SC_LibriSpeech_2spk_adapted1-10 on a compound set with data as similar to your test data as possible. If you look at [Table XIII](https://arxiv.org/pdf/2312.04324), you will see that the bottom of the table, with fine-tuning on the compound set leads to the best results. I have not tried averaging checkpoints from models fine-tuned on different datasets but my guess is that this will not work well. However, if you try it, please let me know how it worked for you as I would be curious to know if it does help.

**Comment by fnlandini** [comment]
Closing for now. Feel free to reopen if necessary
